min_mainnet_k_size: 32

# Send a ping to all peers after ping_interval seconds
ping_interval: 120
self_hostname: &self_hostname "localhost"
daemon_port: 8018
daemon_max_message_size: 50000000 # maximum size of RPC message in bytes
inbound_rate_limit_percent: 100
outbound_rate_limit_percent: 30

# Limit the number of start_full_node worker processes to reduce ram and cpu usage
# This allows users to farm more forks without running out of ram
# Setting this too low reduces sync speed, but a synced node can stay synced with a multiprocessing_limit of 2
# A value higher than 61 takes no effect, as chia limits the workers to 61 (windows server related python bug)
# multiprocessing_limit: 4

network_overrides: &network_overrides
  constants:
    mainnet:
      NETWORK_TYPE: 0
      GENESIS_CHALLENGE: "9a031606d27e61393d6e79f49d9bdc16bb349ebda4db59559d8ef2fbcac34eba"
      GENESIS_PRE_FARM_POOL_PUZZLE_HASH: "a892e26c3e34a23759aadc4cfd532b2753d8996bdccad281fd4818bd060c97a7"
      GENESIS_PRE_FARM_FARMER_PUZZLE_HASH: "0bffceff1ad5edd7218a6aeab129101565c07edb97df3ed7647f7a67f8b66253"
    testnet0:
      NETWORK_TYPE: 1
      GENESIS_CHALLENGE: "6d761c830ce416549b1cb3c3f7808b8f975928d5e3e129b0e1c0a07983e11195"
      GENESIS_PRE_FARM_POOL_PUZZLE_HASH: "777d3118f84ef787b5452db7ece5f9118e9b6ba85d3ce17f5363a14feea1446c"
      GENESIS_PRE_FARM_FARMER_PUZZLE_HASH: "e72a4aea90646aba6598d386f4cea69a4511d9255bd9d57fb468d710aebcc797"
      MIN_PLOT_SIZE: 18
    testnet1:
      NETWORK_TYPE: 1
      GENESIS_CHALLENGE: "078b056bec1c728d3d9f45a4d514d180a9d93f1e73a57d8f1700acf97e0a27f5"
      GENESIS_PRE_FARM_POOL_PUZZLE_HASH: "777d3118f84ef787b5452db7ece5f9118e9b6ba85d3ce17f5363a14feea1446c"
      GENESIS_PRE_FARM_FARMER_PUZZLE_HASH: "e72a4aea90646aba6598d386f4cea69a4511d9255bd9d57fb468d710aebcc797"
      DIFFICULTY_CONSTANT_FACTOR: 10052721566054
      MIN_PLOT_SIZE: 18
    testnet2:
      NETWORK_TYPE: 1
      GENESIS_CHALLENGE: "7a19df165b10d9a1a2ec7010d9be78c3a90e919c07fc95f843ad3cbb3b89baa6"
      GENESIS_PRE_FARM_POOL_PUZZLE_HASH: "777d3118f84ef787b5452db7ece5f9118e9b6ba85d3ce17f5363a14feea1446c"
      GENESIS_PRE_FARM_FARMER_PUZZLE_HASH: "e72a4aea90646aba6598d386f4cea69a4511d9255bd9d57fb468d710aebcc797"
      DIFFICULTY_CONSTANT_FACTOR: 10052721566054
      MIN_PLOT_SIZE: 18
      MEMPOOL_BLOCK_BUFFER: 10
    testnet3:
      NETWORK_TYPE: 1
      GENESIS_CHALLENGE: "812b4b018b53166296a7a76c6009f3cbe2861b18b3fe271ea2589abd595135a5"
      GENESIS_PRE_FARM_POOL_PUZZLE_HASH: "777d3118f84ef787b5452db7ece5f9118e9b6ba85d3ce17f5363a14feea1446c"
      GENESIS_PRE_FARM_FARMER_PUZZLE_HASH: "e72a4aea90646aba6598d386f4cea69a4511d9255bd9d57fb468d710aebcc797"
      DIFFICULTY_CONSTANT_FACTOR: 10052721566054
      MIN_PLOT_SIZE: 18
      MEMPOOL_BLOCK_BUFFER: 10
      EPOCH_BLOCKS: 768
      DIFFICULTY_STARTING: 30
    testnet4:
      NETWORK_TYPE: 1
      GENESIS_CHALLENGE: "68a8e03280ef6c94239508bfefae4c1a73abe83c6249125b961dfba3858a7c41"
      GENESIS_PRE_FARM_POOL_PUZZLE_HASH: "777d3118f84ef787b5452db7ece5f9118e9b6ba85d3ce17f5363a14feea1446c"
      GENESIS_PRE_FARM_FARMER_PUZZLE_HASH: "e72a4aea90646aba6598d386f4cea69a4511d9255bd9d57fb468d710aebcc797"
      DIFFICULTY_CONSTANT_FACTOR: 10052721566054
      MIN_PLOT_SIZE: 18
      NETWORK_TYPE: 1
      MEMPOOL_BLOCK_BUFFER: 10
      EPOCH_BLOCKS: 768
      DIFFICULTY_STARTING: 30
    testnet5:
      NETWORK_TYPE: 1
      GENESIS_CHALLENGE: "706bcb05d4107d10314a10d9845618fa335604db7f9e363676fd4279a5c97d80"
      GENESIS_PRE_FARM_POOL_PUZZLE_HASH: "777d3118f84ef787b5452db7ece5f9118e9b6ba85d3ce17f5363a14feea1446c"
      GENESIS_PRE_FARM_FARMER_PUZZLE_HASH: "e72a4aea90646aba6598d386f4cea69a4511d9255bd9d57fb468d710aebcc797"
      DIFFICULTY_CONSTANT_FACTOR: 10052721566054
      MIN_PLOT_SIZE: 18
      MEMPOOL_BLOCK_BUFFER: 10
      EPOCH_BLOCKS: 768
      DIFFICULTY_STARTING: 30
  config:
    mainnet:
      address_prefix: "heather"
      default_full_node_port: 8008
    testnet0:
      address_prefix: "heather"
    testnet1:
      address_prefix: "heather"
    testnet2:
      address_prefix: "heather"
    testnet3:
      address_prefix: "heather"
    testnet4:
      address_prefix: "heather"
    testnet5:
      address_prefix: "heather"
      default_full_node_port: 8008

selected_network: &selected_network "testnet5"
ALERTS_URL: https://download.heatherblockchain.io/notify/mainnet_alert.txt
CHIA_ALERTS_PUBKEY: 89b7fd87cb56e926ecefb879a29aae308be01f31980569f6a75a69d2a9a69daefd71fb778d865f7c50d6c967e3025937

# public ssl ca is included in source code
# Private ssl ca is used for trusted connections between machines user owns
private_ssl_ca:
  crt: "config/ssl/ca/private_ca.crt"
  key: "config/ssl/ca/private_ca.key"

heather_ssl_ca:
  crt: "config/ssl/ca/heather_ca.crt"
  key: "config/ssl/ca/heather_ca.key"


daemon_ssl:
  private_crt: "config/ssl/daemon/private_daemon.crt"
  private_key: "config/ssl/daemon/private_daemon.key"


# Controls logging of all servers (harvester, farmer, etc..). Each one can be overriden.
logging: &logging
  log_stdout: False  # If True, outputs to stdout instead of a file
  log_filename: "log/debug.log"
  log_level: "INFO"  # Can be CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET
  log_maxfilesrotation: 7 #  Max files in rotation. Default value 7 if the key is not set
  log_syslog: False  # If True, outputs to SysLog host and port specified
  log_syslog_host: "localhost"  # Send logging messages to a remote or local Unix syslog
  log_syslog_port: 514  # UDP port of the remote or local Unix syslog

harvester:
  # The harvester server (if run) will run on this port
  port: 8012
  farmer_peer:
    host: *self_hostname
    port: 8011

  # If True, starts an RPC server at the following port
  start_rpc_server: True
  rpc_port: 8016
  num_threads: 30
  plots_refresh_parameter:
    interval_seconds: 120 # The interval in seconds to refresh the plot file manager
    retry_invalid_seconds: 1200 # How long to wait before re-trying plots which failed to load
    batch_size: 300 # How many plot files the harvester processes before it waits batch_sleep_milliseconds
    batch_sleep_milliseconds: 1 # Milliseconds the harvester sleeps between batch processing


  # If True use parallel reads in chiapos
  parallel_read: True

  logging: *logging
  network_overrides: *network_overrides
  selected_network: *selected_network

  # Plots are searched for in the following directories
  plot_directories: []

  ssl:
    private_crt:  "config/ssl/harvester/private_harvester.crt"
    private_key:  "config/ssl/harvester/private_harvester.key"

  private_ssl_ca:
    crt: "config/ssl/ca/private_ca.crt"
    key: "config/ssl/ca/private_ca.key"

  heather_ssl_ca:
    crt: "config/ssl/ca/heather_ca.crt"
    key: "config/ssl/ca/heather_ca.key"

pool:
  # Replace this with a real puzzle hash
  # heather_target_address: heather102gkhhzs60grx7cfnpng5n6rjecr89r86l5s8xux2za8k820cxsq64ssdg
  logging: *logging
  network_overrides: *network_overrides
  selected_network: *selected_network


farmer:
  # The farmer server (if run) will run on this port
  port: 8011
  # The farmer will attempt to connect to this full node and harvester
  full_node_peer:
    host: *self_hostname
    port: 8008
  harvester_peer:
    host: *self_hostname
    port: 8012

  pool_public_keys: []

  # Replace this with a real puzzle hash
  # heather_target_address: heather102gkhhzs60grx7cfnpng5n6rjecr89r86l5s8xux2za8k820cxsq64ssdg

  # If True, starts an RPC server at the following port
  start_rpc_server: True
  rpc_port: 8015

  # To send a share to a pool, a proof of space must have required_iters less than this number
  pool_share_threshold: 1000
  logging: *logging
  network_overrides: *network_overrides
  selected_network: *selected_network

  ssl:
    private_crt:  "config/ssl/farmer/private_farmer.crt"
    private_key:  "config/ssl/farmer/private_farmer.key"
    public_crt:  "config/ssl/farmer/public_farmer.crt"
    public_key:  "config/ssl/farmer/public_farmer.key"

# Don't run this unless you want to run VDF clients on the local machine.
timelord_launcher:
  # The server where the VDF clients will connect to.
  host: *self_hostname
  port: 8019
  # Number of VDF client processes to keep alive in the local machine.
  process_count: 3
  logging: *logging


timelord:
  # The timelord server (if run) will run on this port
  port: 8010
  # Provides a list of VDF clients expected to connect to this timelord.
  # For each client, an IP is provided, together with the estimated iterations per second.
  vdf_clients:
    ip:
      - *self_hostname
      - localhost
      - 127.0.0.1
    ips_estimate:
      - 150000
  full_node_peer:
      host: *self_hostname
      port: 8008
  # Maximum number of seconds allowed for a client to reconnect to the server.
  max_connection_time: 60
  # The ip and port where the TCP clients will connect.
  vdf_server:
    host: *self_hostname
    port: 8019
  logging: *logging
  network_overrides: *network_overrides
  selected_network: *selected_network
  # fast_algorithm is a faster proof generation algorithm. This speed increase
  # requires much less memory usage and a does not have the risk of OOM that
  # the normal timelord has but requires significantly more cores doing
  # parrallel proof generation and creates a larger and slower to verify
  # resulting proof.
  # An Intel Core i9-10900K can run 2 normal vdf_clients at ~221,000 ips
  # without slowing down but running more than 1 with fast_algorithm will
  # run each vdf_client slower.
  fast_algorithm: False
  # Bluebox (sanatizing Timelord):
  # If set 'True', the timelord will create compact proofs of time, instead of
  # extending the chain. The attribute 'fast_algorithm' won't apply if timelord
  # is running in sanitizer_mode.
  # You must set 'send_uncompact_interval' in 'full_node' > 0 in the full_node
  # section below to have full_node send existing time proofs to be sanitized.
  sanitizer_mode: False

  ssl:
    private_crt:  "config/ssl/timelord/private_timelord.crt"
    private_key:  "config/ssl/timelord/private_timelord.key"
    public_crt:  "config/ssl/timelord/public_timelord.crt"
    public_key:  "config/ssl/timelord/public_timelord.key"

full_node:
  # The full node server (if run) will run on this port
  port: 8008

  # controls the sync-to-disk behavior of the database connection. Can be one of:
  # "on"    enables syncing to disk, minimizes risk of corrupting the DB in
  #         power-loss, disk failure or kernel panics
  # "full"  enables extra syncing to disk for additional safety from
  #         power-failures and kernel panics
  # "off"   disables syncing, lightens disk load and improves performance.
  #         increases risk of corrupting DB in power-loss, disk failure or
  #         kernel panics
  # "auto"  on/off is decided based on a heuristic of how likely a failure is on
  #         the particular system we're running on. Defaults to "full".
  db_sync: auto

  # Run multiple nodes with different databases by changing the database_path
  database_path: db/blockchain_v1_CHALLENGE.sqlite
  peer_db_path: db/peer_table_node.sqlite
  simulator_database_path: sim_db/simulator_blockchain_v1_CHALLENGE.sqlite
  simulator_peer_db_path: sim_db/peer_table_node.sqlite

  # If True, starts an RPC server at the following port
  start_rpc_server: True
  rpc_port: 8014

  # Use UPnP to attempt to allow other full nodes to reach your node behind a gateway
  enable_upnp: True

  # If node is more than these blocks behind, will do a sync (long sync)
  sync_blocks_behind_threshold: 300

  # If node is more than these blocks behind, will do a short batch-sync, if it's less, will do a backtrack sync
  short_sync_blocks_behind_threshold: 20

  # How often to initiate outbound connections to other full nodes.
  peer_connect_interval: 30
  # How long to wait for a peer connection
  peer_connect_timeout: 30
  # Accept peers until this number of connections
  target_peer_count: 80
  # Initiate outbound connections until this number is hit.
  target_outbound_peer_count: 8
  # IPv4/IPv6 network addresses and CIDR blocks allowed to connect even when target_peer_count has been hit.
  # exempt_peer_networks: ["192.168.0.3", "192.168.1.0/24", "fe80::/10", "2606:4700:4700::64/128"]
  exempt_peer_networks: []
  # Accept at most # of inbound connections for different node types.
  max_inbound_wallet: 20
  max_inbound_farmer: 10
  max_inbound_timelord: 5
  # Only connect to peers who we have heard about in the last recent_peer_threshold seconds
  recent_peer_threshold: 6000

  # Send to a Bluebox (sanatizing timelord) uncompact blocks once every
  # 'send_uncompact_interval' seconds. Set to 0 if you don't use this feature.
  send_uncompact_interval: 0
  # At every 'send_uncompact_interval' seconds, send blueboxes 'target_uncompact_proofs' proofs to be normalized.
  target_uncompact_proofs: 100
  # Setting this flag as True, blueboxes will sanitize only data needed in weight proof calculation, as opposed to whole blocks.
  # Default is set to False, as the network needs only one or two blueboxes like this.
  sanitize_weight_proof_only: False
  # timeout for weight proof request
  weight_proof_timeout: 360

  # when enabled, the full node will print a pstats profile to the root_dir/profile every second
  # analyze with chia/utils/profiler.py
  enable_profiler: False

  # this is a debug and profiling facility that logs all SQLite commands to a
  # separate log file (under logging/sql.log).
  log_sqlite_cmds: False

  # List of trusted DNS seeders to bootstrap from.
  # If you modify this, please change the hardcode as well from FullNode.set_server()
  dns_servers:
    - "dns-introducer.heatherblockchain.io"
  farmer_peer:
      host: *self_hostname
      port: 8011
  timelord_peer:
      host: *self_hostname
      port: 8010
  introducer_peer:
      host: introducer.heatherblockchain.io  # Heather AWS introducer IPv4/IPv6
      port: 8009
  wallet_peer:
    host: *self_hostname
    port: 8013
  logging: *logging
  network_overrides: *network_overrides
  selected_network: *selected_network

  ssl:
    private_crt:  "config/ssl/full_node/private_full_node.crt"
    private_key:  "config/ssl/full_node/private_full_node.key"
    public_crt:  "config/ssl/full_node/public_full_node.crt"
    public_key:  "config/ssl/full_node/public_full_node.key"

ui:
   # The ui node server (if run) will run on this port
  port: 8017

  # Which port to use to communicate with the full node
  rpc_port: 8014

  # This SSH key is for the ui SSH server
  ssh_filename: config/ssh_host_key
  logging: *logging
  network_overrides: *network_overrides
  selected_network: *selected_network

  # this is where the electron UI will find its daemon
  # defaults to the one running locally with its private keys
  daemon_host: *self_hostname
  daemon_port: 8018
  daemon_ssl:
    private_crt: config/ssl/daemon/private_daemon.crt
    private_key: config/ssl/daemon/private_daemon.key

introducer:
  host: *self_hostname
  port: 8009
  max_peers_to_send: 20
  # The introducer will only return peers who it has seen in the last
  # recent_peer_threshold seconds
  recent_peer_threshold: 6000
  logging: *logging
  network_overrides: *network_overrides
  selected_network: *selected_network

  ssl:
    public_crt:  "config/ssl/full_node/public_full_node.crt"
    public_key:  "config/ssl/full_node/public_full_node.key"

wallet:
  port: 8013
  rpc_port: 8020

  enable_profiler: False

  # see description for full_node.db_sync
  db_sync: auto

  # The minimum height that we care about for our transactions. Set to zero
  # If we are restoring from private key and don't know the height.
  starting_height: 0
  start_height_buffer: 100  # Wallet will stop fly sync at starting_height - buffer
  num_sync_batches: 50
  initial_num_public_keys: 100
  initial_num_public_keys_new_wallet: 5

  full_node_peer:
    host: *self_hostname
    port: 8008

  testing: False
  database_path: wallet/db/blockchain_wallet_v1_CHALLENGE_KEY.sqlite
  wallet_peers_path: wallet/db/wallet_peers.sqlite

  logging: *logging
  network_overrides: *network_overrides
  selected_network: *selected_network

  target_peer_count: 5
  peer_connect_interval: 60
  # The introducer will only return peers who it has seen in the last
  # recent_peer_threshold seconds
  recent_peer_threshold: 6000

  introducer_peer:
    host: introducer.heatherblockchain.io # Heather AWS introducer IPv4/IPv6
    port: 8009

  ssl:
    private_crt:  "config/ssl/wallet/private_wallet.crt"
    private_key:  "config/ssl/wallet/private_wallet.key"
    public_crt:  "config/ssl/wallet/public_wallet.crt"
    public_key:  "config/ssl/wallet/public_wallet.key"

  trusted_peers:
    trusted_node_1: "config/ssl/full_node/public_full_node.crt"

  short_sync_blocks_behind_threshold: 20
